# Generated by Django 3.1 on 2021-05-08 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210508_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 23, 17, 17, 911976)),
        ),
    ]
