# Generated by Django 3.1 on 2021-05-18 08:54

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engsub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
