# Generated by Django 3.1 on 2021-06-04 07:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engsub', '0005_auto_20210524_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
