# Generated by Django 3.1 on 2021-06-04 08:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engsub', '0006_auto_20210604_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
