# Generated by Django 3.1 on 2021-06-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engsub', '0007_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='show',
            new_name='shows',
        ),
    ]
