# Generated by Django 3.1 on 2021-06-04 08:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engsub', '0008_auto_20210604_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='shows',
        ),
        migrations.AddField(
            model_name='show',
            name='shws',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
