# Generated by Django 3.1 on 2021-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='isteacher',
            field=models.BooleanField(default=False),
        ),
    ]
