# Generated by Django 3.1 on 2021-06-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherlogin', '0003_tmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsg',
            name='notifs',
            field=models.BooleanField(default=False),
        ),
    ]
