# Generated by Django 3.1 on 2021-05-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
