# Generated by Django 3.1 on 2021-05-15 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0002_userdetail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
