# Generated by Django 3.1 on 2021-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0006_subjects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.CharField(default='', max_length=50),
        ),
    ]
