# Generated by Django 3.1 on 2021-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0007_subjects_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subjectincharge',
            field=models.CharField(default='', max_length=50),
        ),
    ]
