# Generated by Django 3.1 on 2021-05-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0008_subjects_subjectincharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='notif',
            field=models.BooleanField(default=False),
        ),
    ]
