# Generated by Django 3.1 on 2021-05-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='showdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('username', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('username', models.CharField(default='', max_length=50)),
                ('qtn', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='addqtn.showdata')),
            ],
        ),
    ]
